version: '3.7'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: my-hit
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  mailhog_server:
    image: mailhog/mailhog:latest
    container_name: mailhog_server
    restart: on-failure
    ports:
      - '8025:8025'

volumes:
  db-data: